kind: Namespace
apiVersion: v1
metadata:
  name: monitoring
  labels:
    name: monitoring

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-config
  namespace: monitoring
data:
  config.yaml: |
    modules:
      pihole_dns:
        prober: dns
        timeout: 3s
        dns:
          preferred_ip_protocol: ip4
          dns_over_tls: false
          query_name: 'google.com'
          query_type: 'A'

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox
  namespace: monitoring
  labels:
    app: blackbox

spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: blackbox
  template:
    metadata:
      labels:
        app: blackbox
    spec:
      containers:
        - name: blackbox
          image: prom/blackbox-exporter:latest
          imagePullPolicy: Always
          command: ['/bin/blackbox_exporter', '--config.file=/config/config.yaml']
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: blackbox-config
